services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dodo-todo-api:latest
    container_name: dodo-todo-api
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
